CREATE TABLE courses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id INT NOT NULL REFERENCES teachers(user_id) ON DELETE RESTRICT,
  title VARCHAR(255) NOT NULL,
  description TEXT,

  course_type VARCHAR(50) NOT NULL CHECK (course_type IN ('programming', 'design', 'marketing', 'business')),
  duration_weeks INT NOT NULL CHECK (duration_weeks > 0),

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL
);

CREATE INDEX idx_courses_teacher_id ON courses(teacher_id);
CREATE INDEX idx_courses_type ON courses(course_type);
